# -*- python -*-

tools  = ['default', 'prefixoptions', 'netcdfcxx4']
env = Environment(tools=tools)
env.Append(CXXFLAGS='-g -Werror')

mkcdf = env.Program('mkcdf.cc')
env.Default(mkcdf)

env.Install('$INSTALL_PREFIX/bin', 'mkcdf')
