# -*- python -*-

tools=['default', 'prefixoptions', 'netcdf']
env = Environment(tools=tools)
env.Append(CXXFLAGS='-g -Werror -Wall')

ncmerge = env.Program('ncmerge.cc')
env.Default(ncmerge)

env.Install('$INSTALL_PREFIX/bin', 'ncmerge')
