# -*- python -*-

tools = ['default', 'prefixoptions', 'netcdf', 'vardb', 'raf']
env = Environment(tools=tools)
env.Append(CCFLAGS='-g -Wall')

#env.Append(LIBS = ['hdf5_hl' 'hdf5'])

sources = Split("""
asc2cdf.cpp
plain.cpp
nasaAmes.cpp
nasaLangley.cpp
""")

asc2cdfH = env.Program(target = 'asc2cdfH', source = sources)
env.Default(asc2cdfH)

env.Install("$INSTALL_PREFIX/bin", 'asc2cdfH')
