#!/bin/csh
#
# This is a wrapper script to drill down to the sample file for each format 
# and test asc2cdf on it. Individual tests reside in the sample file dirs.

# 100hz file in NASA Ames format
cd test/100hz
py.test test_100hz.py
cd ../..

# 10hz file in NASA Ames format
cd test/ames
py.test test_ames.py
cd ../..

# columnar ASCII file with no header other than column headings and time in 
# seconds since Midnight 
cd test/timeSecSinceMidnight
py.test test_timeSecSinceMidnight.py
cd ../..

# 1hz files with times in hh:mm:ss, hhmmss, and secondsSinceMidnight
cd test/hhmmss
py.test test_time.py
cd ../..

# BADC files with subsecond timestep, missing times, and secondsSinceMidnight
cd test/badc
py.test test_badc.py
cd ../
