# -*- python -*-

env = Environment()
env.Append(CCFLAGS='-g -Wall')


#env.Append(LIBS = ['VarDB', 'raf', 'netcdf', 'hdf5_hl', 'hdf5'])
env.Append(LIBS = ['netcdf', 'hdf5_hl', 'hdf5'])

sources = Split("""
asc2cdf.cpp
plain.cpp
nasaAmes.cpp
nasaLangley.cpp
ICARTT.cpp
BADC_CSV.cpp
getmem.cpp
error.cpp
""")

asc2cdf = env.Program(target = 'asc2cdf', source = sources)
env.Default(asc2cdf)

#Alias('install', env.Install(env['INSTALL_PREFIX']+'/bin', asc2cdf))
env.Install ("$INSTALL_PREFIX/bin", 'asc2cdf')
