# -*- python -*-

env = Environment()
env.Append(CCFLAGS='-g -Wall')


env.Append(LIBS = ['netcdf', 'hdf5_hl', 'hdf5'])

sources = Split("""
asc2cdf.cpp
plain.cpp
nasaAmes.cpp
nasaLangley.cpp
ICARTT.cpp
BADC_CSV.cpp
getmem.cpp
error.cpp
""")

asc2cdf = env.Program(target = 'asc2cdf', source = sources)
env.Default(asc2cdf)

env.Install ("$INSTALL_PREFIX/bin", 'asc2cdf')
