#!/usr/bin/env python3

#######################################################################
# Produce IWG1 packets from a netCDF file. If variable is missing from
# netCDF file, maintain blank entries to keep IWG1 structure.
#
# Copyright University Corporation for Atmospheric Research, 2020
#######################################################################

import netCDF4
import pandas as pd
import numpy as np
import sys
import socket
import argparse
import time
import io
import os
import warnings
warnings.filterwarnings('ignore')

# get arguments from command line
parser = argparse.ArgumentParser(description='A program to produce IWG1 packets from a netCDF file \
                                  If a variable is missing from a netCDF file, maintains blank \
                                  entries to keep IWG1 structure.')
parser.add_argument("input_file", help="netCDF file to convert")
parser.add_argument("-o", "--output_file", help="If you want to write to an output file, include path to output file.")
parser.add_argument("-d", "--delay", help="Optional conversion interval delay in microseconds")
parser.add_argument("-u", "--UDP", type=bool, const=True, nargs="?", default=False,
                    help="Provide this if you want to emulate realtime. Boolean to put program into UDP mode. Default is false. Only provide \
                     '-u' with nothing following")
parser.set_defaults(feature=False)
parser.add_argument("-v", "--extravars", help="File containing comma separated list of vars")
parser.add_argument("-so", "--standard_out", type=bool, const=True, nargs="?",
                    default=False, help="Optional argument for standard out. \
                    If you don't provide, file writes to output file, and that's it. Only provide \
                     '-so' with nothing following")
parser.add_argument("-hn", "--hostname_to_send_to", help="Optional argument to define host")
parser.add_argument("-p", "--port_number", type=int, help="Optional argument to set port #, \
                    otherwise uses 7071")
parser.add_argument("-k", "--key_word_platform", help="Optional argument to set platform e.g.\
                     WB57, C130, WKA, GV, LEAR")
if len(sys.argv) == 1:
    parser.print_help(sys.stderr)
    sys.exit(1)
args = parser.parse_args()

if args.output_file is not None and args.UDP:
    sys.exit("Output file option set and UDP set to True. Only one can be set.")
elif args.output_file is not None and args.delay is not None:
    print("Output file and conversion interval arguments provided. Igoring conversion interval.")
elif args.UDP is False and args.hostname_to_send_to is not None:
    sys.exit("You have UDP output set to False but you have provided a hostname.")
elif args.UDP and args.port_number is not None:
    sys.exit("You have UDP output set to False but you have provided a port number.")
else:
    pass

# default interval to 1 second but use argument if provided
input_file = args.input_file
if args.delay is not None:
    interval = float(args.delay)/1000000.
else:
    interval = 1

# configure UDP broadcast if argument is provided
if args.UDP:
    UDP_OUT = True
    # if port # arg is provided, use that
    if args.port_number is not None:
        UDP_PORT = args.port_number
    # otherwise use 7071
    else:
        UDP_PORT = 7071
    # if hostname is provided, use that
    if args.hostname_to_send_to is not None:
        hostname = args.hostname_to_send_to
    # otherwise get hosthame
    else:
        hostname = socket.gethostname()
        print(hostname)
    UDP_IP = socket.gethostbyname(hostname)
else:
    UDP_OUT = False

if args.key_word_platform is not None:
    platform = args.key_word_platform
else:
    pass


#######################################################################
# define function to convert data to IWG1 format
#######################################################################

def buildIWG():

    # read the input file to convert
    nc = netCDF4.Dataset(input_file, mode='r')
    iwg1_vars_list = ["GGLAT", "GGLON", "GGALT", "NAVAIL", "PALTF",
                      "HGM232", "GGSPD", "TASX", "IAS", "MACH_A", "VSPD",
                      "THDG", "TKAT", "DRFTA", "PITCH", "ROLL", "SSLIP",
                      "ATTACK", "ATX", "DPXC", "RTX", "PSXC", "QCXC",
                      "PCAB", "WSC", "WDC", "WIC", "SOLZE", "Solar_El_AC",
                      "SOLAZ", "Sun_Az_AC"]

    # Detect if this is a highrate or samplerate file by checking for sps dimensions
    highrate_dims = [dim for dim in nc.dimensions if dim.startswith('sps')]
    is_highrate = len(highrate_dims) > 0

    # Determine the maximum sample rate for expanding time
    max_sps = 1
    if is_highrate:
        for dim in highrate_dims:
            sps_value = nc.dimensions[dim].size
            if sps_value > max_sps:
                max_sps = sps_value

    # extract the time variable from the netCDF file
    df = {}
    TIME = nc.variables["Time"]
    base_dtime = netCDF4.num2date(TIME[:], TIME.units)

    # For highrate or samplerate files, create subsecond timestamps
    if is_highrate and max_sps > 1:
        # Create an array of subsecond offsets
        subsec_offsets = [i / float(max_sps) for i in range(max_sps)]
        # Expand time to include all subsecond samples
        expanded_times = []
        for base_time in base_dtime:
            for offset in subsec_offsets:
                expanded_times.append(base_time + pd.Timedelta(seconds=offset))
        # Format with millisecond precision: YYYYMMDDThhmmss.fff
        dtime = pd.Series([t.strftime('%Y%m%dT%H%M%S.%f')[:-3] for t in expanded_times])
    else:
        dtime = pd.Series(base_dtime).astype(str)
        dtime = dtime.str.replace(":", "")
        dtime = dtime.str.replace("-", "")
        dtime = dtime.str.replace(" ", "T")
    if args.output_file is None and args.UDP is None:
        dtime = dtime.iloc[-1:]
        for i in iwg1_vars_list:
            try:
                if i in list(nc.variables.keys()):
                    var_data = nc.variables[i]
                    # Handle highrate variables
                    if is_highrate and len(var_data.shape) > 1:
                        output = var_data[-1, :]  # Get last time step, all subsecond samples
                    else:
                        output = var_data.iloc[-1:] if hasattr(var_data, 'iloc') else var_data[-1:]
                elif i not in list(nc.variables.keys()):
                    output = pd.DataFrame(columns=[i]).iloc[-1:]
                else:
                    pass
            except Exception:
                print(("Error in extracting variable "+i+" in "+input_file))
            df[i] = pd.DataFrame(output)
    else:
        dtime = dtime[:]

        for i in iwg1_vars_list:
            try:
                if i in list(nc.variables.keys()):
                    var_data = nc.variables[i][:]
                    # Handle highrate variables - flatten to one row per subsecond sample
                    if is_highrate and len(var_data.shape) > 1:
                        # Variable has subsecond dimension - reshape to flatten
                        if var_data.shape[1] == max_sps:
                            # This variable matches max sample rate - use as-is
                            output = var_data.flatten()
                        else:
                            # This variable has fewer samples per second - repeat values
                            sps_ratio = max_sps // var_data.shape[1]
                            output = np.repeat(var_data.flatten(), sps_ratio)
                    else:
                        # 1Hz variable - repeat for each subsecond sample
                        if is_highrate and max_sps > 1:
                            output = np.repeat(var_data, max_sps)
                        else:
                            output = var_data
                elif i not in list(nc.variables.keys()):
                    if (i == "GSF"):
                        try:
                            var_data = nc.variables["GSPD"][:]
                            print("*********NOTICE: VARIABLE GSF NOT FOUND IN NETCDF FILE, USING VARIABLE GSPD*********")
                            # Handle highrate for GSF/GSPD
                            if is_highrate and len(var_data.shape) > 1:
                                if var_data.shape[1] == max_sps:
                                    output = var_data.flatten()
                                else:
                                    sps_ratio = max_sps // var_data.shape[1]
                                    output = np.repeat(var_data.flatten(), sps_ratio)
                            else:
                                if is_highrate and max_sps > 1:
                                    output = np.repeat(var_data, max_sps)
                                else:
                                    output = var_data
                        except Exception as e:
                            print(e)
                    elif (i == "TTX"):
                        try:
                            var_data = nc.variables["RTX"][:]
                            print("**********NOTICE: Variable TTX NOT FOUND IN NETCDF FILE, USING VARIABLE RTX*********")
                            # Handle highrate for TTX/RTX
                            if is_highrate and len(var_data.shape) > 1:
                                if var_data.shape[1] == max_sps:
                                    output = var_data.flatten()
                                else:
                                    sps_ratio = max_sps // var_data.shape[1]
                                    output = np.repeat(var_data.flatten(), sps_ratio)
                            else:
                                if is_highrate and max_sps > 1:
                                    output = np.repeat(var_data, max_sps)
                                else:
                                    output = var_data
                        except Exception as e:
                            print(e)
                    else:
                        # Missing variable - create empty array of correct length
                        if is_highrate and max_sps > 1:
                            output_len = len(base_dtime) * max_sps
                            output = np.full(output_len, np.nan)
                        else:
                            output = pd.DataFrame(columns=[i])[:]
                else:
                    pass
            except Exception:
                print(("Error in extracting variable "+i+" in "+input_file))
            df[i] = pd.DataFrame(output)
    global iwg
    iwg = pd.concat([dtime, df["GGLAT"].astype(float).round(decimals=5),
                    df["GGLON"].astype(float).round(decimals=5),
                    df["GGALT"].astype(float).round(decimals=2),
                    df["NAVAIL"].astype(float).round(decimals=2),
                    df["PALTF"].astype(float).round(decimals=2),
                    df["HGM232"].astype(float).round(decimals=2),
                    df["GSF"].astype(float).round(decimals=2),
                    df["TASX"].astype(float).round(decimals=2),
                    df["IAS"].astype(float).round(decimals=2),
                    df["MACH_A"].astype(float).round(decimals=2),
                    df["VSPD"].astype(float).round(decimals=2),
                    df["THDG"].astype(float).round(decimals=2),
                    df["TKAT"].astype(float).round(decimals=2),
                    df["DRFTA"].astype(float).round(decimals=2),
                    df["PITCH"].astype(float).round(decimals=2),
                    df["ROLL"].astype(float).round(decimals=2),
                    df["SSLIP"].astype(float).round(decimals=2),
                    df["ATTACK"].astype(float).round(decimals=2),
                    df["ATX"].astype(float).round(decimals=2),
                    df["DPXC"].astype(float).round(decimals=2),
                    df["TTX"].astype(float).round(decimals=2),
                    df["PSXC"].astype(float).round(decimals=2),
                    df["QCXC"].astype(float).round(decimals=2),
                    df["PCAB"].astype(float).round(decimals=2),
                    df["WSC"].astype(float).round(decimals=2),
                    df["WDC"].astype(float).round(decimals=2),
                    df["WIC"].astype(float).round(decimals=2),
                    df["SOLZE"].astype(float).round(decimals=2),
                    df["Solar_El_AC"].astype(float).round(decimals=2),
                    df["SOLAZ"].astype(float).round(decimals=2),
                    df["Sun_Az_AC"].astype(float).round(decimals=2)], axis=1, ignore_index=True)

    try:
        iwg.insert(loc=0, column='PID', value=platform)
    except Exception:
        iwg.insert(loc=0, column='IWG1', value='IWG1')
    if args.output_file is None and args.UDP is None:
        iwg[0] = iwg[0].shift(-1)
    else:
        pass


    if args.extravars is not None:
        with open(args.extravars) as file:
            for line in file:
                additional_vars_list = line.split()
        extravars = {}
        extra_output = {}
        for i in additional_vars_list:
            print('Additional Variables: ' + i)
            try:
                if i in list(nc.variables.keys()):
                    output = nc.variables[i].iloc[-1:]
                elif i not in list(nc.variables.keys()):
                    output = pd.DataFrame(columns=[i]).iloc[-1:]
                else:
                    pass
            except Exception:
                print(("Error in extracting variable "+i))
            extravars[i] = pd.DataFrame(extra_output)
        try:
            extravars = pd.concat(extravars, axis=1, ignore_index=False)
        except Exception as e:
            print(e)
        try:
            iwg = pd.concat([iwg, extravars], axis=1, ignore_index=False)
        except Exception as e:
            print(e)
    else:
        pass

    iwg = iwg.fillna('')
    iwg = iwg.astype(str)
    return iwg


######################################################################
# define main function
#######################################################################

def main():

    buildIWG()
    if args.output_file is not None:
        iwg.to_csv(args.output_file, header=False, index=False)
    elif args.UDP:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        iwg.to_csv("output.txt", header=False, index=False)
        with io.open("output.txt", "r") as udp_packet:
            lines = udp_packet.readlines()
            while len(lines) != 0:
                MESSAGE = lines[0]
                message = MESSAGE.translate("[]'")
                message = message.rstrip()
                print(message)
                sock.sendto(message.encode(), (UDP_IP, UDP_PORT))
                lines.pop(0)
                time.sleep(float(interval))
    else:
        input_path = os.path.splitext(input_file)
        iwg.to_csv(input_path[0]+".iwg1", header=False, index=False)
        if args.standard_out is not None:
            with io.open(input_path[0]+".iwg1", "r") as udp_packet:
                lines = udp_packet.readlines()[-1]
                while len(lines) != 0:
                    MESSAGE = str(lines)
                    message = MESSAGE.translate("[]'")
                    message = message.rstrip()
                    print(message)
                    time.sleep(float(interval))
#######################################################################
# main
#######################################################################


if __name__ == "__main__":
    main()
