# -*- python -*-

tools = ['default', 'prefixoptions']
env = Environment(tools=tools)
#env.Append(CXXFLAGS='-g -Werror')

#qt4Modules = Split('QtGui QtCore QtNetwork')
#if not env.EnableQt4Modules(qt4Modules):
#    raise StopError("qt4 modules could not be enabled.")

#sources = ['nc2iwg1.cc']

#nc2iwg1 = env.Program(target = 'nc2iwg1', source = sources)

#env.Default(nc2iwg1)

env.Install("$INSTALL_PREFIX/bin", 'nc2iwg1.py')
