# -*- python -*-

import os
env = Environment(platform = 'posix',ENV= os.environ)
env['JLOCAL'] = os.environ['JLOCAL']

# print env.Dump()

#env.Program('ncstat')

Alias('install', env.Install('$JLOCAL/bin', 'ncstat'))
