# -*- python -*-

tools=['default', 'prefixoptions', 'netcdfcxx4']
env = Environment(tools=tools)
env.Append(CXXFLAGS='-g -Werror')

ncvarlist = env.Program('ncvarlist.cc')
env.Default(ncvarlist)

env.Install('$INSTALL_PREFIX/bin', 'ncvarlist')
