# -*- python -*-
import os
# Define the source files
support_files = [
    './lib/nc2asc/write_data.py',
    './lib/nc2asc/process_nc.py',
    './lib/nc2asc/read_batch.py',
    # Add any other new files here
]
tools  = ['default', 'prefixoptions']
env = Environment(tools=tools)

env.Install('$INSTALL_PREFIX/bin', 'nc2asc')
env.Install('$INSTALL_PREFIX/lib/nc2asc', './lib/nc2asc/header1.txt')
env.Install('$INSTALL_PREFIX/lib/nc2asc', './lib/nc2asc/header1_ames.txt')
env.Install('$INSTALL_PREFIX/lib/nc2asc', './lib/nc2asc/header2.txt')
env.Install('$INSTALL_PREFIX/lib/nc2asc', './lib/nc2asc/header2_ames.txt')
for file in support_files:
    env.Install('$INSTALL_PREFIX/lib/nc2asc', file)
